packages:
  # - 'packages/common/debug'
  # - 'toolchains/protocols-toolchain'
  # - 'toolchains/toolchain-node-library'
  - 'packages/common/codec-protobuf'
  - 'packages/common/protobuf-compiler'
  - 'packages/common/protobuf-test'
