version: 1
stateMachine: "test-guest"
startSequence:
  commands:
    - createProfile:
        foo: 'bar'
    
testSequences:
  - commands:
    - syncClient:
        id: "test-agent-client-sync"
        msg: "client-alive-ready"
        to: "gravity-agent-server-sync"
    - acceptSpaceInvitation:
        swarmKey: "62815fecc2448f37aab2b77c92f5a73a238407d8eb3ff15eeb4037bda4c075ae"
