version: 1
stateMachine: "test-host"
startSequence:
  commands:
    - createProfile:
        # Just to satisfy the parse and protobuf schema.
        foo: 'bar'


testSequences:
  - commands:
    - createSpace:
        id: "space-1"
    - createSpaceInvitation:
        id: "space-1"
        swarmKey: "62815fecc2448f37aab2b77c92f5a73a238407d8eb3ff15eeb4037bda4c075ae"

stopSequence:

