on:
  push:
    branches-ignore:
      - main

name: check
jobs:
  check:
    runs-on: [self-hosted, dind-actions-runner]
    timeout-minutes: 25
    strategy:
      matrix:
        node-version: [16.0]
        temp: [1,2,3,4,5]
        temp2: [1,2,3,4,5]
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          clean: true
      - name: Check, install and build
        run: |
          \. "$NVM_DIR/nvm.sh" && nvm use ${{ matrix.node-version }}
          npm install -g @microsoft/rush pnpm
          sudo ./common/scripts/install-dependencies.sh
          npx playwright@1.11.0 install-deps

          # Install dependencies
          echo "::group::Install"
          node common/scripts/install-run-rush.js install
          echo "::endgroup::"

          # Build with tests
          node common/scripts/github-actions-folding.js node common/scripts/install-run-rush.js build --to @dxos/browser-tests
          cd packages/gravity/browser-tests
          node ../../../common/scripts/github-actions-folding.js node ../../../common/scripts/install-run-rushx.js build:test
